version: "3.5"
services:
  restapi:
    image: ghcr.io/arquisoft/dede_en2a/restapi:latest
    ports:
      - "5000:5000"
  webapp:
    image: ghcr.io/arquisoft/dede_en2a/webapp:latest
    ports:
      - "3000:3000"
    depends_on:
      - restapi
      - carriersapi
