@url = http://localhost:5000

GET {{url}}/users/list

###
GET {{url}}/users/findByEmail/pablog@gmail.com

###
POST  {{url}}/users/create
Content-Type: application/json

{
    "name": "dani",
    "surname": "alvarez",
    "email": "danialvz@gmail.com"
}

###
DELETE {{url}}/users/deleteByEmail/pablolopez@gmail.com

###
PUT {{url}}/users/update/pablog@gmail.com

Content-Type: application/json

{
    
}