@url = http://localhost:5000

GET {{url}}/users/list

###
GET {{url}}/users/findByEmail/pablog@gmail.com

###
POST  {{url}}/users/create
Content-Type: application/json

{
    "name": "pablo",
    "surname": "lopez",
    "email": "pablol@gmail.com",
    "password": "bph59woegryjse45"
}

###
DELETE {{url}}/users/deleteByEmail/pablolopez@gmail.com

###
POST {{url}}/users/update/sitom@gmail.com

Content-Type: application/json
{
    "name": "sitos",
    "surname": "martinezs"
}