@url = http://localhost:5000

GET {{url}}/products/list

###
GET {{url}}/products/findByCode/0007

###
POST  {{url}}/products/create
Content-Type: application/json

{
    "code": "1447",
    "name": "Camiseta Real Sporting Jony",
    "price": 10.99,
    "description": "Ni de coña chaval",
    "stock": 5
}

###
DELETE {{url}}/products/delete/0

###
POST {{url}}/products/update/46
Content-Type: application/json

{
    "weight": 0.5
}

###
GET {{url}}/products/order/desc

###
GET {{url}}/products/filter&order/Electronics&asc
