[[section-architecture-constraints]]
== Architecture Constraints


[role="arc42help"]
****
.Contents
Any requirement that constrains software architects in their freedom of design and implementation decisions or decision about the development process. These constraints sometimes go beyond individual systems and are valid for whole organizations and companies.

.Motivation
Architects should know exactly where they are free in their design decisions and where they must adhere to constraints.
Constraints must always be dealt with; they may be negotiable, though.

.Form
Simple tables of constraints with explanations.
If needed you can subdivide them into
technical constraints, organizational and political constraints and
conventions (e.g. programming or versioning guidelines, documentation or naming conventions)
****

=== Table 1. Technical Constraints

[options="header",cols="1,3"]
|===
|Constraint| Explanation
|React | The React Framework will be used to implement the application
|Typescript| The programming language to be used to implement the application 
|Solid| Solid Specifications are required to preserve customer's privacy 
|Github| The version control is managed through GitHub, Git Bash. It provides tools for organizing and sharing the work. 
|===


=== Table 2. Organizational Constaints

[options="header",cols="1,3"]
|===
|Constraint| Explanation
|App development| There is a due date to develop and finish the app
|Team | The team creating the project is built up by 5 members
|Testing| Different scenarios will be taken into account to test a correct behaviour of the app 
|===
