[[section-building-block-view]]


== Building Block View
[role="arc42help"]


=== Level 1 Whitebox Overall System
[role="arc42help"]

[plantuml, "level1", png]
----
Actor Juan
Component DeDe
Component pod as "Pod's service"

Juan -right-> DeDe: interacts with

DeDe <-right-> pod: gets data
----
****
Motivation::

Dede application is the general structure of a system in which users will have the possibility to send their deliveries to any place they want and check and be updated of their state. 
All the data that belongs to the user is stored safely in their POD's.


Contained Building Blocks::
[options="header",cols="1,3"]
|===
|Name| Description
|User | Client of the application which will interact with it
|Dede | System developed to be used by the users. Through it information in the PODs will be taken.  
|Pod's service| Has the aim to access each user personal pod
|===
****

=== Level 2
[role="arc42help"]
[plantuml, "level2", png]
----
Actor Juan
Component DeDe {
    Component ui as "User Interface"
    Component da as "Data Access"
    Database db as "MongoDB"
}
Component pod as "Pod's service"

Juan -right-> ui
ui <-right-> da: data

da <--> db: data flow
da <--> pod: get address
----

Motivation::

Shows how the application will work internally in general terms. The client through the interface will get the data requested by using the Data Access layer.


Contained Building Blocks::
[options="header",cols="1,3"]
|===
|Name| Description
|User Interface | The user will interact with this interface to request any information about the deliveries or program any service.
|Data Access | The layer that will provide and request information from and to the pods and the database
|MongoDB | Database used to stored the minimum data needed from the users
|===


=== Level 3
[role="arc42help"]

[plantuml, "level3", png]
----
Actor Juan

Component Interface{
    Component vi as "Views"{
       Component ho as "Home"
       Component sh as "Shopping cart"
       Component sho as "Shop"
       Component lo as "Sign in"
       Component re as "Sign up"
       Component out as "Log out"       
       Component my as "Orders"
       Component ck as "Check out"
    }    
}

Component DataAccess{
       Component sol as "Solid"
       Component res as "RestApi"
       Component pay as "PayPal Api"
       Component de as "Delivery Api"
}

Component pod as "Pod's service"
Database db as "MongoDB"
Juan -right->Interface: interacts

re -right-> sol
ck -down-> sol

re-right->res
sho-right->res
lo-right->res
sh-right->res
my-right->res


ck -down-> pay
ck-down->de


sol <-down-> pod:acceses
res <-down-> db:data
----
****
Motivation::

Detailed structure of the system application. Focused in the components of the User Interface and Data Access.


Contained Building Blocks::
[options="header",cols="1,3"]
|===
|Name| Description
|Views | Parts of the application which the user is going to interact with during experience with the system
|Home |  Initial screen for the application
|Shop | View where all the products are show 
|Shopping cart | The user has a shoppin cart where he will can see the products previosly selected and change the amount of the product.
|Sign in |  Here the user will log in into their personal account if they have previously created one
|Sign up | Allows the client to create a new account for the application
|Orders | Here the user can find any information related with their deliveries, like their state or details
|Log out | It signs out the application from the last user.
|Check out | In the check out the user can finish with his purchase.
|Restapi | The application asks the restapi for the information needed and this asks and returns it from the MongoDB.
|PayPal Api | Api from PayPal used in the checkout for the users to pay their purchase.
|===
****
