[[section-building-block-view]]


== Building Block View
[role="arc42help"]
****
****

=== Level 1 Whitebox Overall System
[role="arc42help"]
****
****

[plantuml, "level1", png]
----
Actor Juan
Component DeDe
Component pod as "Pod's service"

Juan -right-> DeDe: interacts with

DeDe <-right-> pod: gets data
----

Motivation::

Dede application is the general structure of a system in which users will have the possibility to send their deliveries to any place they want and check and be updated of their state. 
All the data that belongs to the user is stored safely in their POD's.


Contained Building Blocks::
[options="header",cols="1,3"]
|===
|Name| Description
|User | Client of the application which will interact with it
|Dede | System developed to be used by the users. Through it information in the PODs will be taken.  
|Pods provider | Has the aim to access each user personal pod
|User pod | Where the user's information is saved with total security 
|===


=== Level 2
[role="arc42help"]
****
****
[plantuml, "level2", png]
----
Actor Juan
Component DeDe {
    Component ui as "User Interface"
    Component da as "Data Access"
    Database db as "MongoDB"
}
Component pod as "Pod's service"

Juan -right-> ui
ui <-right-> da: data

da <--> db: data flow
da <--> pod: get address
----

Motivation::

Shows how the application will work internally in general terms. The client through the interface will get the data requested by using the Data Access layer.


Contained Building Blocks::
[options="header",cols="1,3"]
|===
|Name| Description
|User Interface | The user will interact with this interface to request any information about the deliveries or program any service.
|Data Access | The layer that will provide and request information from and to the pods and the database
|MongoDB | Database used to stored the minimum data needed from the users
|===


=== Level 3
[role="arc42help"]
****
****

[plantuml, "level3", png]
----
Actor Juan

Component Interface{
    Component vi as "Views"{
       Component lo as "Log in"
       Component re as "Register"
       Component ho as "Home"
       Component loc as "Location"
       Component no as "Notifications"
       Component my as "My deliveries"
       Component ac as "Account"
       Component out as "Sign out"
       Component sh as "Shopping cart"
    }    
}

Component DataAccess{
       Component sol as "Solid"
       Component res as "RestApi"
}

Component pod as "Pod's service"
Database db as "MongoDB"
Juan -right->Interface: interacts
lo -down-> sol
re -down-> sol
ho -down-> sol
loc -down-> sol
no -down-> sol
my -down-> sol
ac -down-> sol
out -down-> sol
sh -down->sol
lo -down-> res
my -down-> res
ac -down-> res

sol <-down-> pod:acceses
res <-down-> db:data
----
Motivation::

Detailed structure of the system application. Focused in the components of the User Interface and Data Access.


Contained Building Blocks::
[options="header",cols="1,3"]
|===
|Name| Description
|Views | Parts of the application which the user is going to interact with during experience with the system
|Log in |  Here the user will log in into their personal account if they have previously created one
|Register | Allows the client to create a new account for the application
|Home |  Initial screen for the application
|Location | Shows the current location of the user that is using the app
|Notifications | The notification will make the client to be up to date with their deliveries  
|My deliveries | Here the user can find any information related with their deliveries, like their state or their location 
|Account | In this part the client is going to be able to perform any operation in their account like introducing new data or removing it
|Sign out | It signs out the application from the last user.
|===
