[[section-deployment-view]]


== Deployment View

[role="arc42help"]
****
.Content
The deployment view describes:

 1. the technical infrastructure used to execute your system, with infrastructure elements like geographical locations, environments, computers, processors, channels and net topologies as well as other infrastructure elements and

2. the mapping of (software) building blocks to that infrastructure elements.

Often systems are executed in different environments, e.g. development environment, test environment, production environment. In such cases you should document all relevant environments.

Especially document the deployment view when your software is executed as distributed system with more then one computer, processor, server or container or when you design and construct your own hardware processors and chips.

From a software perspective it is sufficient to capture those elements of the infrastructure that are needed to show the deployment of your building blocks. Hardware architects can go beyond that and describe the infrastructure to any level of detail they need to capture.

.Motivation
Software does not run without hardware.
This underlying infrastructure can and will influence your system and/or some
cross-cutting concepts. Therefore, you need to know the infrastructure.

.Form

Maybe the highest level deployment diagram is already contained in section 3.2. as
technical context with your own infrastructure as ONE black box. In this section you will
zoom into this black box using additional deployment diagrams:

* UML offers deployment diagrams to express that view. Use it, probably with nested diagrams,
when your infrastructure is more complex.
* When your (hardware) stakeholders prefer other kinds of diagrams rather than the deployment diagram, let them use any kind that is able to show nodes and channels of the infrastructure.
****

=== Infrastructure Level 1

[plantuml, "07_DeploymentView", png]
----
node AzureServer{
    node DockerContainer2 {
        component CarrierAPI
    }
    node DockerContainer1 {
        component RestApi
    }
    node DockerContainer3 {
        component WebApp
    }
    
}

node UserDevice {
    node WebBrowser {
        component WebAppImage
    }
}

database MongoDBAtlas {
    component MongoDB
}

Actor User

cloud SOLID_POD
cloud BingMaps
cloud Geoapify
cloud PayPalAPI


User -r-> WebAppImage
RestApi -u-> MongoDB : "access information"
WebAppImage -d-> SOLID_POD : "access user data"
WebAppImage -d-> BingMaps : "provides maps and route image"
WebAppImage -r-> Geoapify : "get near places"
WebAppImage -d-> PayPalAPI : "provides paying system"
RestApi -r-> WebApp : "supply data"
WebApp -d-> WebAppImage : "shows on user device"
RestApi -l-> CarrierAPI : "calculate routes prices"
----

.Motivation
For development and testing the execution environment will be on each student's machine. But for the production phase it will be deployed in a Dockerized environment hosted on Azure. Our goal is to have a correct understanding of Docker, the infrastructure over which our system will be deployed.


.Quality and/or performance features
The performance on the deployment build will depend on the user's internet connection as well as on the Azure servers used for the deployment of the app, since those factors are out of our hand. But the performance of the application can be maxed with some coding approaches, then, privacy and security will be our main concerns to aim for the best and more secure expirience for the user. 

.Mapping of building blocks to infrastructure
[options="header",cols="1,2"]
|===
|Element|Description
| WebApp | The front end of our application. It will be rendered by a web browser, which will be executed over the user device
| RestApi | The back-end of our application. It will run on the Azure server.
| MongoDB | Database of our application
| POD provider | Solid pods will be provided by Solid Community
| Carrier API | API created to provide the costs for shipping 
|===
