[[section-deployment-view]]
== Deployment View

=== Infrastructure Level 1

[plantuml, "07_DeploymentView", png]
----
node AzureServer{
    node DockerContainer {
        component RestApi
    }
}

node UserDevice {
    node WebBrowser {
        component WebApp
    }
}

database DatabaseServer {
    component MongoDB
}

Actor User

cloud SOLID_POD
cloud CarrierAPI
cloud BingMaps
cloud Geoapify
cloud PayPalAPI

RestApi -u-> MongoDB : "access information"
WebApp -l-> SOLID_POD : "access user data"
WebApp -l-> BingMaps : "provides maps and route image"
WebApp -r-> Geoapify : "get near places"
WebApp -r-> PayPalAPI : "provides paying system"
RestApi -d-> WebApp : "supply data"
RestApi -r-> CarrierAPI : "calculate routes prices"
WebApp <-d- User
----

.Motivation
For developing and testing, the execution environment will be running on the maching of each student. But, at the production stage, it will be deployed in a _Dockerized_ environment hosted on _Azure_. Our goal is to have a correct understanding of _Docker_: the infrastructure over which our system will be deployed.

.Quality and/or performance features
The performance on the deployment build will depend on the user's internet connection as well as on the _Azure_ servers used for the deployment of the app. Since those factors are out of our hand, we can do nothing with that. But the performance of the application can be maxed out with some coding approaches - then - privacy and security will be our main concerns for achieving the best and securest user's experience. 

.Mapping of building blocks to infrastructure
[options="header",cols="1,2"]
|===
|Element|Description

|*WebApp*
|The frontend of our application. It will be rendered by a web browser which will be executed ont the user's device.

|*RestAPI*
|The back-end of our application. It will run on the Azure server.

|*MongoDB*
|Database chosen for the application

|*POD provider*
|_Solid PODs_ will be provided by _solidcommunity.org_ or _Inrupt_.

|*Carrier API*
|API created to calculate the costs of the shipping for different carriers.
|===
