[[section-concepts]]
== Cross-cutting Concepts

=== Domain model
[plantuml, "DomainModel", png]
----
object User{
    webId : String
    role : String
    isVerified : boolean
}

object Product{
    code: String
    name: String
    description: String
    price: double
    stock: int
    image: String
    category: String
    weight: double
}

object Order{
    code: String
    webId: String
    address: String
    products: Product[]
    date: Date
    subtotalPrice: double
    shippingPrice: double
    totalPrice: double
    receivedDate: Date
}

object Review{
    webId: String
    productCode: String
    rating: int
    comment: String
}

Order *--> User
Order o--> Product
Review *--> Product
Review *--> User
----

=== Security

_Security_ is a very important concept in the context of a system. As we are managing information from users, it is important to ensure that the information is safe and that the system is not compromised. So, we decided to store in our system the minimum information necessary and obtain the other from the _PODs_. Also we decided to encrypt the users' passwords, if any.

Also, we added security in the _backend_ to prevent unauthorized requests to the RestAPI, as well as for preventing the execution of malicious code.

=== Testability

In order to ensure the correct functioning of the system, we decided to implement _unit tests_ for most of the components. Also we implemented _e2e tests_ to check that the full system is working properly and that the user experience is good.
