name: CI for ASW2122

on:
  release:
    types: [published]

jobs:
  unit-test-webapp:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: webapp
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npm test
      - uses: codecov/codecov-action@v2
  unit-test-restapi:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: restapi
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npm test
      - uses: codecov/codecov-action@v2
  #e2e-tests:
  #needs: [unit-test-webapp, unit-test-restapi]
  #runs-on: ubuntu-latest
  #steps:
  # - uses: actions/checkout@v2
  #- uses: actions/setup-node@v2
  #  with:
  #   node-version: 16
  #- run: npm --prefix webapp install
  #- run: npm --prefix restapi install
  #- run: npm --prefix webapp run build
  #- run: npm --prefix webapp run test:e2e
  docker-push-webapp:
    name: Push webapp Docker Image to GitHub Packages
    runs-on: ubuntu-latest
    env:
      API_URI: http://${{ secrets.DEPLOY_HOST }}:5000
      MAPBOX_KEY: ${{ secrets.REACT_APP_MAPBOX_KEY }}
      BING_KEY: ${{ secrets.REACT_APP_BING_KEY }}
      PAYPAL_CLIENT_ID: ${{ secrets.REACT_APP_PAYPAL_CLIENT_ID }}
      GEOAPIFY_KEY: ${{ secrets.REACT_APP_GEOAPIFY_KEY }}
      SKIP_PREFLIGHT_CHECK: true
    needs: [unit-test-webapp, unit-test-restapi]
    steps:
      - uses: actions/checkout@v2
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: arquisoft/dede_en2a/webapp
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PUSH_TOKEN }}
          registry: ghcr.io
          workdir: webapp
          buildargs: API_URI, MAPBOX_KEY, BING_KEY, PAYPAL_CLIENT_ID, GEOAPIFY_KEY
  docker-push-restapi:
    name: Push restapi Docker Image to GitHub Packages
    runs-on: ubuntu-latest
    env:
      PORT: ${{ secrets.PORT }}
      MONGO_DB_URI: ${{ secrets.MONGO_DB_URI }}
      NODE_ENV: ${{ secrets.NODE_ENV }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      AUTH_EMAIL: ${{ secrets.AUTH_EMAIL }}
      AUTH_PASS: ${{ secrets.AUTH_PASS }}
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
    needs: [unit-test-webapp, unit-test-restapi]
    steps:
      - uses: actions/checkout@v2
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: arquisoft/dede_en2a/restapi
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PUSH_TOKEN }}
          registry: ghcr.io
          workdir: restapi
          buildargs: PORT, MONGO_DB_URI, NODE_ENV, JWT_SECRET, AUTH_EMAIL, AUTH_PASS, SENDGRID_API_KEY
  docker-push-carriers:
    name: Push carriers restapi Docker Image to GitHub Packages
    runs-on: ubuntu-latest
    env:
      CARRIERS_DB_URI: ${{ secrets.CARRIERS_DB_URI}}
    needs: [unit-test-webapp, unit-test-restapi]
    steps:
      - uses: actions/checkout@v2
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: arquisoft/dede_en2a/carriersapi
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PUSH_TOKEN }}
          registry: ghcr.io
          workdir: carrier-service-api
          buildargs: CARRIERS_DB_URI
  deploy:
    name: Deploy over SSH
    runs-on: ubuntu-latest
    needs: [docker-push-restapi, docker-push-webapp, docker-push-carriers]
    steps:
      - name: Deploy over SSH
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          user: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          command: |
            wget https://raw.githubusercontent.com/Arquisoft/dede_en2a/master/docker-compose-deploy.yml -O docker-compose.yml
            docker-compose stop
            docker-compose rm -f
            docker-compose pull   
            docker-compose up -d
